language: node_js

node_js:
  - "stable"

script:
  - yarn run lint
  - yarn run build
  - yarn run test -- --verbose

before_cache:
  - yarn run unlink

cache:
  yarn: true
  directories:
    - node_modules
