language: node_js

node_js:
  - "stable"

script:
  - yarn run lint
  - yarn run test -- --verbose
  - yarn run test-actual -- --verbose -u

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; fi

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
