language: node_js

node_js:
  - "stable"

script:
  - yarn run lint
  - yarn run test -- --verbose
  - yarn run test-actual -- --verbose -u

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  fast_finish: true
